server:
  port: 8882
spring:
  application:
    name: wfm-service
  jackson:
        default-property-inclusion: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs


