server:
  port: 8880
spring:

  application:
    name: common-service
  cloud:
    discovery:
      enabled: true
      eureka:
        client:
          service-url:
            defaultZone: http://localhost:8761/eureka/



springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs