server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: common-service
          uri: lb://COMMON-SERVICE
          predicates:
            - Path=/api/common/**




        - id: wfm-service
          uri: lb://WFM-SERVICE
          predicates:
            - Path=/api/wfm/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


